### ISSUE TITLE
Step 1: Keptn and k6 Running with Job Executor Service

### ISSUE THREAD

**Issue by agardnerIT** [keptn-sandbox/k6-service#1]
Before proceeding with more complex integrations, ensure the "basic" k6 integration works [as shown here](https://artifacthub.io/packages/keptn/keptn-integrations/k6-keptn-integration) and that you **fully** understand how and why it works.

1. Install Keptn
2. Install [Job Executor Service](https://github.com/keptn-contrib/job-executor-service)
3. Create a project / service / stage / sequence
4. Configure job executor service to listen for your `taskname.triggered` event
5. Configure job executor service to trigger the k6 container in response to this event

@jainammm  FYI

**Comment by jainammm** [comment]
Okay, got it... Will test this out first :)

**Comment by agardnerIT** [comment]
@jainammm can you document the "issue" and the "fix" for the JES issue you encountered so that others can potentially learn from it. Thanks.

**Comment by jainammm** [comment]
hey @agardnerIT, where should I document the final flow of K6 using JES? 
and what should be the structure of K6 services and sequence in the final tutorial?
