### ISSUE TITLE
Discuss: Building K6 extensions and running test instead of asking user to do it

### ISSUE THREAD

**Issue by jainammm** [keptn-sandbox/k6-service#4]
# Topic
- How to incorporate the below flow in Keptn? 

```jobs:
  k6_local_test:
    name: k6 counter extension run
    runs-on: ubuntu-latest
    container: docker://golang:1.17-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build xk6-counter binary
        run: xk6 build --with github.com/mstoykov/xk6-counter@latest

      - name: Run k6 extension test
        run: ./k6 run extension/script.js
```
# References

- https://k6.io/blog/load-testing-using-github-actions/#running-k6-extensions
- https://k6.io/docs/extensions/bundle-builder/
- https://github.com/grafana/xk6#custom-builds

**Comment by agardnerIT** [comment]
I believe we can close this. I think we're at an agreement that we don't model this (entirely) in Keptn.
The user brings their k6 container (binary inside a container that they have built in CI) and we run it with JES

**Comment by jainammm** [comment]
yes, we tried multiple things for this
* try building K6 extension using a golang docker image and a shell script
* but as Christian mentioned [here](https://keptn.slack.com/archives/CNRCGFU3U/p1657019077867629?thread_ts=1657000898.196059&cid=CNRCGFU3U) it's not advisable to use JES that way
