### ISSUE TITLE
Listen to Keptn's `sh.keptn.event.test.triggered` CloudEvent

### ISSUE THREAD

**Issue by jainammm** [keptn-sandbox/k6-service#9]
As a first step towards building the K6 service, make sure the Service is able to listen to Keptn's `sh.keptn.event.test.triggered` event and print some dummy logs on the console.

**Comment by agardnerIT** [comment]
Status update please

**Comment by jainammm** [comment]
yes, the PR has been raised for it here #15 

I'll merge it once I finalize the changes we want to merge... the automation on GitHub Actions is remaining
